name: mtrust_api_guard
description: A package to generate and compare API docs
homepage: https://github.com/emdgroup/mtrust-api-guard/
version: 5.1.0
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  analyzer: ">=7.4.5 <11.0.0"
  build: ">=2.4.1 <5.0.0"
  code_builder: ^4.8.0
  conventional: ^0.4.0
  glob: ^2.1.3
  build_config: ^1.1.1
  dart_style: ^3.1.0
  args: ^2.4.0
  path: ^1.9.1
  collection: ^1.19.1
  yaml: ^3.1.3
  mason_logger: ^0.3.3
  pub_semver: ^2.2.0
  yaml_edit: ^2.2.2
  json_annotation: ^4.9.0
  http: ^1.4.0
  crypto: ^3.0.7
executables:
  mtrust_api_guard:
dev_dependencies:
  test: any
  json_serializable: ^6.9.5
  build_runner: ^2.4.15
  flutter_lints: ">=1.0.0 <7.0.0"
