name: mtrust_api_guard
description: A package to generate and compare API docs
homepage: https://github.com/emdgroup/mtrust-api-guard/
version: 0.0.1
environment:
  sdk: ">=2.17.0 <4.0.0"
dependencies:
  analyzer: ">=6.2.0 <8.0.0"
  build: ">=2.4.1 <4.0.0"
  code_builder: ^4.8.0
  glob: ^2.0.2
  build_config: ^1.1.1
  source_gen: ">=1.4.0 <4.0.0"
  dart_style: ">=2.3.4 <4.0.0"
  flutter_lints: ">=1.0.0 <7.0.0"
  args: ^2.4.0
  path: ^1.9.1
  collection: ^1.19.1
executables:
  mtrust_api_guard:
